# Generated by Django 3.0.8 on 2020-08-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(blank=True, max_length=200, verbose_name='ISBN')),
                ('SHUMING', models.CharField(blank=True, max_length=200, null=True, verbose_name='书名')),
                ('ZUOZHE', models.CharField(blank=True, max_length=200, null=True, verbose_name='作者')),
                ('CHUBANSHE', models.CharField(blank=True, max_length=200, null=True, verbose_name='出版社')),
                ('CHUPINFANG', models.CharField(blank=True, max_length=200, null=True, verbose_name='出品方')),
                ('FUBIAOTI', models.CharField(blank=True, max_length=200, null=True, verbose_name='副标题')),
                ('YUANZUOMING', models.CharField(blank=True, max_length=200, null=True, verbose_name='原作名')),
                ('YIZHE', models.CharField(blank=True, max_length=200, null=True, verbose_name='译者')),
                ('CHUBANNIAN', models.CharField(blank=True, max_length=200, null=True, verbose_name='出版年')),
                ('YESHU', models.CharField(blank=True, max_length=200, null=True, verbose_name='页数')),
                ('DINGJIA', models.CharField(blank=True, max_length=200, null=True, verbose_name='定价')),
                ('ZHUANGZHEN', models.CharField(blank=True, max_length=200, null=True, verbose_name='装帧')),
                ('CONGSHU', models.CharField(blank=True, max_length=200, null=True, verbose_name='丛书')),
                ('GUOJI', models.CharField(blank=True, max_length=200, null=True, verbose_name='国籍')),
                ('JIANJIE', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('FENGMIAN', models.CharField(blank=True, max_length=200, null=True, verbose_name='封面')),
            ],
        ),
    ]
