# Generated by Django 3.0.8 on 2020-08-25 03:40

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dreams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kingdom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LEIBIE', models.CharField(blank=True, max_length=50, verbose_name='分类')),
            ],
        ),
        migrations.CreateModel(
            name='Phylum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LEIBIE', models.CharField(blank=True, max_length=50, verbose_name='分类')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BIAOTI', models.CharField(blank=True, max_length=300, verbose_name='标题')),
                ('ZHENGWEN', ckeditor.fields.RichTextField(verbose_name='正文')),
                ('CHUANGJIANSHIJIAN', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ZUIHOUSHIJIAN', models.DateTimeField(auto_now=True, verbose_name='最后编辑时间')),
                ('BIAOQIAN', models.CharField(blank=True, max_length=500, verbose_name='标签')),
                ('DAFENLEI', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dreams.Kingdom', verbose_name='大分类')),
                ('XIAOFENLEI', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dreams.Phylum', verbose_name='小分类')),
                ('ZUOZHE', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
        ),
    ]
