# Generated by Django 3.0.8 on 2020-08-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0003_phylum_father'),
    ]

    operations = [
        migrations.AddField(
            model_name='kingdom',
            name='BIEMING',
            field=models.CharField(blank=True, max_length=50, verbose_name='别名'),
        ),
        migrations.AddField(
            model_name='phylum',
            name='BIEMING',
            field=models.CharField(blank=True, max_length=50, verbose_name='别名'),
        ),
    ]
