# Generated by Django 3.0.8 on 2020-08-26 08:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0004_auto_20200826_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ZHENGWEN',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='正文'),
        ),
    ]
