# Generated by Django 3.0.8 on 2020-09-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0005_auto_20200826_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oracle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ZUOZHE', models.CharField(blank=True, max_length=100, verbose_name='作者')),
                ('ZUOPIN', models.CharField(blank=True, max_length=100, verbose_name='作品')),
                ('ZHENGWEN', models.CharField(blank=True, max_length=300, verbose_name='正文')),
            ],
        ),
    ]
