# Generated by Django 3.0.8 on 2020-09-17 04:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0006_oracle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oracle',
            name='ZHENGWEN',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='正文'),
        ),
    ]
